services:
  zap:
    image: owasp/zap2docker-stable
    ports:
      - 8090:8090
      - 8080:8080
    command: 
      - zap-webswing.sh
     #- zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
