web:
  image: 'gitlab/gitlab-ce:13.8.4-ce.0'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - '/srvgit/gitlab/config:/etc/gitlab'
    - '/srvgit/gitlab/logs:/var/log/gitlab'
    - '/srvgit/gitlab/data:/var/opt/gitlab'
